### ISSUE TITLE
Not Using Trinkets

### ISSUE THREAD

**Issue by emilyploszaj** [Globox1997/BackSlot#71]
I've come to notice that this mod adds slots to the player's screen handler and doesn't use Trinkets, causing incompatibilities that need to be resolved by manually editing values in a config. The mod also seems to have multiple required dependencies out of the gate, I'm curious why BackSlot doesn't use Trinkets? Trinkets exists to compatibly do what BackSlot wants and should provide all of the functionality to have it be used like you do, without requiring you to go through all the effort to reimplement it and cause incompatibilities. I'm happy to discuss adding features if you believe Trinkets is missing functionality that you need, but I hope this issue can be resolved soon.

**Comment by wsesrdtf** [comment]
Maybe it's  because of the bag mod that uses the backslot.

**Comment by ginsm** [comment]
How likely do you think it is that you'd switch to using Trinkets @Globox1997? I'm mostly wondering if I should go ahead and write a compat layer for BackSlot for one of my mods or if I should just wait (as my mod is already compatible with Trinkets as-is). :thinking:

**Comment by Globox1997** [comment]
When I made this mod trinkets and curious already exist but those were in more or less early stages and rewrites were are on the plan. Another reason for me was, it is a bigger challenge to do stuff without libs :D 
As you said emily, it is possible to make those mods compatible with editing values in the config so I don't see a real necessity to update backslot and make it depend on trinkets. 
Since I'm working on my thesis and have other mods I'm working on, my time is definitely strongly limited.

**Comment by Balakay420** [comment]
@ginsm how do you edit the config ti allow the backslots to trinkets? :D

**Comment by Globox1997** [comment]
Since I have no plans to use trinkets, this issue gets closed.
