### ISSUE TITLE
Items drop with Grave mod

### ISSUE THREAD

**Issue by Kuggle01** [Globox1997/BackSlot#75]
Items in the backslots will still drop on the ground with this grave mod https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger

**Comment by Globox1997** [comment]
At [https://github.com/B1n-ry/Youre-in-grave-danger/blob/1.18.2/src/main/java/com/b1n_ry/yigd/mixin/LivingEntityMixin.java#L58](https://github.com/B1n-ry/Youre-in-grave-danger/blob/1.18.2/src/main/java/com/b1n_ry/yigd/mixin/LivingEntityMixin.java#L58) the items get added to the grave item list and since in the PlayerInventory class only those three "main, armor, offHand" are public instead of the "combinedInventory" (where BackSlot adds its items) which contains all three of these :/

My guess is that an AW onto the combinedInventory would work fine and then this can be used.

**Comment by Globox1997** [comment]
Added better compat with other grave mods. yigd with [https://github.com/Globox1997/BackSlot/commit/f3f3aef39f18f2be844d1badb67d8c7caca50069](https://github.com/Globox1997/BackSlot/commit/f3f3aef39f18f2be844d1badb67d8c7caca50069)
It looks like the different grave mods just copied the same code xD
Except for [https://www.curseforge.com/minecraft/mc-mods/universal-graves](https://www.curseforge.com/minecraft/mc-mods/universal-graves), this one works perfectly fine.
The compat I have with all other gravestone mods is not perfect since they don't use the combined inventory field (which is private, could be changed with an AW)

Bad compat:
[https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[https://www.curseforge.com/minecraft/mc-mods/gravestones](https://www.curseforge.com/minecraft/mc-mods/gravestones)
[https://www.curseforge.com/minecraft/mc-mods/charm](https://www.curseforge.com/minecraft/mc-mods/charm) (preserving totem)
Good compat:
[https://www.curseforge.com/minecraft/mc-mods/universal-graves](https://www.curseforge.com/minecraft/mc-mods/universal-graves)
